/**
 * Generates the weekly recap and money snapshot for every commissioner league,
 * and writes them into the repo as markdown.
 *
 * Runs in CI on a Tuesday cron (after Monday Night Football settles), where the
 * runner has real network access to Sleeper. The output is committed, so the
 * recap archive is versioned in git rather than living only in one browser's
 * localStorage.
 *
 *   npx tsx scripts/weekly-recap.ts            # write files
 *   npx tsx scripts/weekly-recap.ts --dry-run  # print, change nothing
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { getNFLState, getUserByUsername, getUserLeagues } from "../src/lib/sleeper";
import { findLeagueProfile } from "../src/lib/league-config";
import { loadLeagueMoney } from "../src/lib/league-money";
import { computeWeekRecap } from "../src/lib/league-data";
import { formatCommishRecap, findWeekTopStarters } from "../src/lib/format-recap";
import { formatBowlResultLine, formatUpcomingBowlBlock, formatUpcomingHonorableBlock } from "../src/lib/bowl-narrative";
import { standingsThroughWeek, summarizeWeek } from "../src/lib/payouts";
import { resolvePlayers } from "../src/lib/players";
import { DEFAULT_SLEEPER_USERNAME, defaultSeason } from "../src/lib/app-defaults";

const DRY_RUN = process.argv.includes("--dry-run");
const OUT_DIR = path.join(process.cwd(), "recaps");

function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

async function main() {
  const username = DEFAULT_SLEEPER_USERNAME;
  if (!username) {
    console.error("No DEFAULT_SLEEPER_USERNAME configured; nothing to do.");
    return;
  }

  const user = await getUserByUsername(username);
  if (!user) {
    console.error(`Sleeper has no user "${username}".`);
    process.exitCode = 1;
    return;
  }

  const state = await getNFLState();
  const season = state?.season ?? defaultSeason();
  const leagues = await getUserLeagues(user.user_id, season);
  const commishLeagues = leagues.filter((l) => findLeagueProfile(l.name));

  if (commishLeagues.length === 0) {
    console.log(`No commissioner-profiled leagues found for ${username} in ${season}.`);
    return;
  }

  for (const league of commishLeagues) {
    const money = await loadLeagueMoney(league.league_id);
    if (!money) {
      console.log(`Skipping ${league.name}: no profile resolved.`);
      continue;
    }

    // The latest week that actually has scores, rather than trusting the NFL
    // state's week pointer, which advances mid-week.
    const week = money.ledger.weeksPlayed.at(-1);
    if (!week) {
      console.log(`Skipping ${league.name}: no completed weeks yet.`);
      continue;
    }

    const data = await computeWeekRecap(league.league_id, week);
    if (!data) {
      console.log(`Skipping ${league.name}: could not build week ${week} recap.`);
      continue;
    }

    // The high scorer's top starters are fully derivable from Sleeper, so resolve
    // their names here same as the app does. The "Matchup of the Week" bowl-game
    // picks live in browser localStorage, unreachable from this CI script — those
    // fall back to the same bracket-placeholder text the app shows when no pick
    // has been made, for the commish to fill in by hand.
    const summary = summarizeWeek(money.ledger, week);
    const leaderIds = summary?.highScorer
      ? findWeekTopStarters(summary.highScorer.rosterId, data.games).map((l) => l.playerId)
      : [];
    const resolved = leaderIds.length > 0 ? await resolvePlayers(leaderIds) : [];
    const playerNames: Record<string, string> = {};
    for (const p of resolved) playerNames[p.playerId] = p.name;

    const recap = formatCommishRecap({
      data,
      ledger: money.ledger,
      playerNames,
      bowlResultLine: formatBowlResultLine("👑", null, data.games),
      honorableResultLine: formatBowlResultLine("🏆", null, data.games),
      upcomingBowlLines: formatUpcomingBowlBlock(null, week + 1, data.games, data.standingsAfter),
      upcomingHonorableLines: formatUpcomingHonorableBlock(null, week + 1, data.games),
    });
    const standings = standingsThroughWeek(money.ledger, week);

    const body = [
      `<!-- Generated by scripts/weekly-recap.ts. Edits here will be kept;`,
      `     the script only writes a file that does not already exist. -->`,
      "",
      `# ${league.name} — Week ${week}`,
      "",
      `_${season} season · generated ${new Date().toISOString().slice(0, 10)}_`,
      "",
      "```",
      recap.trimEnd(),
      "```",
      "",
      "## Money through this week",
      "",
      "| Manager | Earned |",
      "| --- | ---: |",
      ...standings.map((r) => `| ${r.name} | $${r.amount} |`),
      "",
      `Paid out to date: **$${money.ledger.paidToDate}** of the $${money.ledger.reconciliation.pot} pot ` +
        `($${money.ledger.reconciliation.finalTotal} held for the top 3).`,
      "",
    ].join("\n");

    const dir = path.join(OUT_DIR, `${slug(league.name)}-${season}`);
    const file = path.join(dir, `week-${String(week).padStart(2, "0")}.md`);

    if (DRY_RUN) {
      console.log(`--- would write ${path.relative(process.cwd(), file)} ---`);
      console.log(body);
      continue;
    }

    await fs.mkdir(dir, { recursive: true });
    // Never clobber a recap that already exists — by the time the cron re-runs,
    // the commish may have replaced the generated draft with the real writeup.
    try {
      await fs.access(file);
      console.log(`Kept existing ${path.relative(process.cwd(), file)}`);
      continue;
    } catch {
      // not there yet, safe to write
    }
    await fs.writeFile(file, body);
    console.log(`Wrote ${path.relative(process.cwd(), file)}`);
  }
}

main().catch((err) => {
  console.error("Weekly recap generation failed:", err);
  process.exitCode = 1;
});
